const tutorialChallengesText = [
    "Get 5 C notes in a row",
    "Get 5 D notes in a row",
    "Get 5 random notes in a row",
    "Get 5 E notes in a row",
    "Get 5 random notes in a row",
    "Get 5 F notes in a row",
    "Get 5 random notes in a row",
    "Get 5 G notes in a row",
    "Get 5 random notes in a row",
    "Get 5 A notes in a row",
    "Get 5 random notes in a row",
    "Get 5 B notes in a row",
    "Get 5 random notes in a row",
    "Get 5 C# notes in a row",
    "Get 5 random notes in a row",
    "Get 5 D# notes in a row",
    "Get 5 random notes in a row",
    "Get 5 F# notes in a row",
    "Get 5 random notes in a row",
    "Get 5 G# notes in a row",
    "Get 5 random notes in a row",
    "Get 5 A# notes in a row",
    "Get 5 random notes in a row",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tutorial Complete",
]

export default tutorialChallengesText