const tutorialTitles = [
    "Introducing Middle C",
    "Introducing D",
    "Challenge",
    "Introducing E",
    "Challenge",
    "Introducing F",
    "Challenge",
    "Introducing G",
    "Challenge",
    "Introducing A",
    "Challenge",
    "Introducing B",
    "Challenge",
    "Introducing C#",
    "Challenge",
    "Introducing D#",
    "Challenge",
    "Introducing F#",
    "Challenge",
    "Introducing G#",
    "Challenge",
    "Introducing A#",
    "Challenge",
    "Congratulations!",
    "Flats",
    "Key Signatures",
    "G Major",
    "F Major",
    "Naturals",
    "Time to play",
]

export default tutorialTitles